### ISSUE TITLE
Blurry results for MIP360 dataset

### ISSUE THREAD

**Issue by GeJintian** [hbb1/2d-gaussian-splatting#136]
Hello, thank you so much for your great work! Recently when I tried 2DGS on MIP360 flowers dataset, I got a blurry result as in the picture. 

For training, I use the simple commandline:

```python train.py -s m360/flowers -m output/m360/flowers```

And for rendering, I tried both bounded and unbounded methods:

```python render.py -s m360/flowers -m output/m360/flowers```
```python render.py -s m360/flowers -m output/m360/flowers --unbounded```

Both rendering methods couldn't give a satisfying result. So, is there something wrong with my training method? And are there any special arguments I missed for training and rendering?
![Screenshot from 2024-08-06 10-25-31](https://github.com/user-attachments/assets/9e0c22de-88ea-4973-bb07-67be48eb1c69)

**Comment by hbb1** [comment]
Hi. This is normal to 2DGS (and original 3DGS),  because we both use a similar densificiation strategy.  More advanced strategies has resolved this. You may be interested in related works like [GOF](https://arxiv.org/pdf/2404.10772), [TrimGS](https://trimgs.github.io/), and [AbsGS](https://arxiv.org/abs/2404.10484).

**Comment by hbb1** [comment]
FYI, this [issue](https://github.com/hbb1/2d-gaussian-splatting/issues/133) is also related.

**Comment by GeJintian** [comment]
Thank you so much for your quick reply! Your suggestion is crucial for my project. I will look into it. Many thanks again.
