### ISSUE TITLE
gaussians spread out at no background dataset

### ISSUE THREAD

**Issue by qianqiuzzz** [hbb1/2d-gaussian-splatting#22]
When I use a dataset with no background, gaussians begins to become scattered, they appear in the background position after 7k iterations, causing black areas to appear in the mesh. Is this phenomenon caused by Normal Consistency regularization? Is there any way to avoid this problem？
![image](https://github.com/hbb1/2d-gaussian-splatting/assets/142602778/0d514cf6-99df-46fb-9160-5ec8d5f7bcb4)
![image](https://github.com/hbb1/2d-gaussian-splatting/assets/142602778/ba2d3a1c-81cb-46cd-ba87-fe3ab2c488f1)

**Comment by hbb1** [comment]
Hi, We haven't tested our algorithm for scenes without background. Because the floater can learn fake background color, an intrinsic ambiguity of volume rendering, the normal consistency loss may treat it as solid object and may spread these floaters.  I suggest you move the start iteration of normal consistency ``after densitification`` , e.g.,  15k, when the floaters may have been effectively cleaned by ``reset opacity``. Or if you have a background mask, just use it to mask the regularization loss. Hope these will help.
