### ISSUE TITLE
Training loss can not converge with custome cropped dataset.

### ISSUE THREAD

**Issue by hot-dog** [hbb1/2d-gaussian-splatting#23]
Thanks for your great work! I tried with my own data and the training loss could not converge, all the training parameters are default. My data has been cropped and the  principal point does not locate on the center of the image, i have modified the projection matrix accordingly and these modifications works fine with 3DGS, but do not work with 2DGS. I have no idea how to fix this, could you please give me some advises? Thank you:)
![image](https://github.com/hbb1/2d-gaussian-splatting/assets/5945046/bb8f509e-9b86-4a83-89ca-38380f00a08e)

**Comment by hbb1** [comment]
Hi, we currently don't support non-ideal pinhole camera yet. Since we use a different projection method, modifying the projection matrix just doesn't work for 2DGS. To support this, we need to modify the rasterizer to support non-center intrinsic here https://github.com/hbb1/diff-surfel-rasterization/blob/main/cuda_rasterizer/forward.cu#L208.  You can refer to this [issue](https://github.com/hbb1/2d-gaussian-splatting/issues/5#issuecomment-2099806902) for making your data center.

**Comment by hot-dog** [comment]
> Hi, we currently don't support non-ideal pinhole camera yet. Since we use a different projection method, modifying the projection matrix just doesn't work for 2DGS. To support this, we need to modify the rasterizer to support non-center intrinsic here https://github.com/hbb1/diff-surfel-rasterization/blob/main/cuda_rasterizer/forward.cu#L208. You can refer to this [issue](https://github.com/hbb1/2d-gaussian-splatting/issues/5#issuecomment-2099806902) for making your data center.

Thanks for you reply, i get it, i will modify the rasterizer code and try again.

**Comment by hbb1** [comment]
Hi, can you check this PR https://github.com/hbb1/2d-gaussian-splatting/pull/27 to see if the current implementation works for you?

**Comment by hot-dog** [comment]
Sorry for the late reply, i modified the reaterizer code to adapt to principal point offset and the training can converge.

**Comment by Egolee0713** [comment]
@hot-dog hi, can you tell how to modified the reaterizer code to adapt to principal point offset?
