### ISSUE TITLE
Incomplete Mesh

### ISSUE THREAD

**Issue by JiajieLi7012** [hbb1/2d-gaussian-splatting#92]
Hello,

Thanks for your great work. I tried 2DGS on the video below which only covers the scene from certain angles with the default setting and I got the following incomplete mesh. I'm wondering if there is a way to improve the mesh result or if the result is limited because of the nature of the input data. Any help would be appreciated. Thanks in advance.

https://github.com/hbb1/2d-gaussian-splatting/assets/77574492/8cc4b5a4-12b9-4a38-a7de-162094ea7ff6

![mesh_result00](https://github.com/hbb1/2d-gaussian-splatting/assets/77574492/001b534d-dc82-442d-b8a5-a02ca5f9c147)

**Comment by ansj11** [comment]
I have the same problem, Have you solved this problem

**Comment by hbb1** [comment]
What is the depth_trunc then? My depth range is estimated using the camera traj. If you camera traj is not circular, there may be a problem.

**Comment by JiajieLi7012** [comment]
Thanks for your response. The depth_trunc is 22.29. The camera traj is not circular as shown in the image below.

![video6_colmap_result](https://github.com/hbb1/2d-gaussian-splatting/assets/77574492/acd3897d-bb2e-4a7e-b2a8-c390d95dcf2d)

**Comment by JiajieLi7012** [comment]
Hi @ansj11, it looks like this is related to the `depth_truc` value. I tried to increase the `depth_truc` value from around 22 to 40 in this scene and got much better results as below. But I still don't know how to mitigate the problem systematically and I hope @hbb1 could share more insights later when he is available.

![increased_depth_truc00](https://github.com/hbb1/2d-gaussian-splatting/assets/77574492/af73306b-7b34-4e03-960d-e54a480d453c)

**Comment by hbb1** [comment]
Thank you for your report.  In order to export a mesh, it is necessary to have some prior information to determine the export location. When the center and radius are known, the 'depth_trunc' is set slightly larger than the radius. My code is designed to automatically estimate this based on the camera trajectory, assuming it follows a circular path. For indoor scenes, you can use information from the depth map to determine the 'depth_trunc', such as the maximum depth value.
